---
name: tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: buildkite/plugin-tester:latest
      volumes:
        - "${{github.workspace}}:/plugin"
    steps:
        uses: actions/checkout@v2
      - name: tests
        run: bats tests/

  lint:
    runs-on: ubuntu-latest
    container:
      image: buildkite/plugin-linter:latest
      volumes:
        - "${{github.workspace}}:/plugin"
    steps:
      - uses: actions/checkout@v2
      - name: lint
        run: lint

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
